---
# tasks file for check_reboot
- name: check if reboot is needed
  stat: path=/var/run/reboot-required
  register: check_reboot

- name: Get the Tailscale IPv4 address
  ansible.builtin.command: tailscale ip -4
  register: tailscale_ip
  changed_when: false
  when: check_reboot.stat.exists

- name: Send notification message via Slack
  community.general.slack:
    token: "{{ webhook_token }}"
    msg: '{{ group_names }} node `{{ inventory_hostname }}` <https://login.tailscale.com/admin/machines/{{ tailscale_ip.stdout | trim }}|{{ ansible_host }}> requires a reboot'
  delegate_to: localhost
  when: check_reboot.stat.exists
