---
# tasks file for setup_tailscale
- name: Set tailscale_auth_key if environment variable exists
  set_fact:
    tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
  when: lookup('env', 'TAILSCALE_AUTH_KEY') | length > 0
  no_log: true

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Add Tailscale GPG apt Key
  get_url:
    url: https://pkgs.tailscale.com/stable/debian/{{ ansible_lsb.codename }}.noarmor.gpg
    dest: /etc/apt/keyrings/tailscale-archive-keyring.gpg
    mode: 0644

- name: Add Tailscale repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian {{ ansible_lsb.codename }} main"
    filename: tailscale
    state: present
    update_cache: no

- name: Force apt-get update allowing expired snapshot metadata
  command: apt-get update -o Acquire::Check-Valid-Until=false

- name: "Install Tailscale packages"
  ansible.builtin.apt:
    name:
      - "tailscale"
    state: present
    allow_downgrade: yes

- name: Start tailscale
  command: tailscale up --authkey {{ tailscale_auth_key }} --ssh
  when: tailscale_auth_key is defined
  no_log: true
