---
- name: Create libvirt-guests config file
  copy:
    src: files/libvirt-guests
    dest: /etc/default/libvirt-guests
    owner: root
    group: root
    mode: '0644'

- name: Install libvirt and libvirt dependencies
  apt:
    name: 
      - dnsmasq
      - qemu-system-x86
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - qemu-utils
      - libnss-libvirt
    state: present
    update_cache: yes

- name: Remove virt-manager if it exists
  apt:
    name: 
      - virt-manager
    state: absent

- name: Enable and start libvirtd service
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: Check libvirt 'default' network state
  command: virsh net-info default
  register: net_info
  changed_when: false
  failed_when: false

- name: Start the default libvirt network if it is not active
  command: virsh net-start default
  when: net_info.rc == 0 and net_info.stdout | regex_search('Active:\s+no') | bool

- name: Enable autostart for the default libvirt network
  command: virsh net-autostart default

- name: Modify nsswitch.conf
  copy:
    src: files/nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
