---
# tasks file for setup_cache
- name: Ensure /opt/provisioner-cache directory exists
  file:
    path: /opt/provisioner-cache
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create docker compose file
  copy:
    src: files/docker-compose.yaml
    dest: /opt/provisioner-cache/docker-compose.yaml
    owner: root
    group: root
    mode: 0644

- name: Create provisioner-cache file
  copy:
    src: files/cache.conf
    dest: /opt/provisioner-cache/cache.conf
    owner: root
    group: root
    mode: 0644

- name: Create systemd service file for provisioner cache
  copy:
    src: files/provisioner-cache.service
    dest: /etc/systemd/system/provisioner-cache.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and start Provisioner Cache service
  service:
    name: provisioner-cache
    enabled: yes
    state: started
