---
# -----------------------------------------------------------------------------
# Discover which SSH port is open.
# This runs first to find the correct port without failing.
# -----------------------------------------------------------------------------
- name: Discover Open SSH Port
  hosts: all
  gather_facts: false
  roles:
    - discover_ssh_port

# -----------------------------------------------------------------------------
# Use Discovered SSH Port to Setup the Server
# This runs after the SSH port has been discovered.
# -----------------------------------------------------------------------------
- name: Setup Server
  hosts: all
  become: yes
  vars:
    ansible_port: "{{ discovered_ssh_port }}"
  roles:
    - setup_server
    - setup_libvirt
    - setup_docker
    - setup_tailscale
    - setup_cache
