---
- name: Setup Libvirt on the target node
  hosts: all
  become: yes
  tasks:
    - name: Remove systemd-resolved
      apt:
        name: systemd-resolved
        state: absent
      ignore_errors: yes

    - name: Create dns configuration file
      template:
        src: ../templates/resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Set hostname if inventory_hostname is valid
      set_fact:
        hostname: "{{ inventory_hostname }}"
      failed_when: not inventory_hostname or inventory_hostname | length == 0

    - name: Set tailscale_auth_key if environment variable exists
      set_fact:
        tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
      when: lookup('env', 'TAILSCALE_AUTH_KEY') | length > 0
      no_log: true

    - name: Set timezone to UTC
      timezone:
        name: UTC

    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
        use: debian

    - name: Update /etc/hosts file
      template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

    - name: Modify dnsmasq file
      template:
        src: ../templates/dnsmasq.j2
        dest: /etc/default/dnsmasq
        owner: root
        group: root
        mode: 0644

    - name: create directory for htoprc
      file:
        path:  /root/.config/htop
        state: directory

    - name: Create htoprc
      template:
        src: ../templates/htoprc.j2
        dest: /root/.config/htop/htoprc
        owner: root
        group: root
        mode: 0644

    - name: Install libvirt, libvirt dependencies, and other packages
      apt:
        name: 
          - dnsmasq
          - qemu-system-x86
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virtinst
          - virt-manager
          - qemu-utils
          - xmlstarlet
          - jq
          - htop
          - curl
          - tmux
          - ca-certificates
        state: present
        update_cache: yes
    
    - name: Install tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      when: tailscale_auth_key is defined
        
    - name: Start tailscale
      command: tailscale up --authkey {{ tailscale_auth_key }} --ssh
      when: tailscale_auth_key is defined
      no_log: true

    - name: Enable and start libvirtd service
      service:
        name: libvirtd
        enabled: yes
        state: started

    - name: Enable and start the default libvirt network
      shell: |
        virsh net-start default
        virsh net-autostart default
      changed_when: false

    - name: Modify sshd_config
      template:
        src: ../templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted

    - name: Remove all users except root
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - glueops
        - admin
        - debian
    
    - name: Add public key to authorized_keys
      authorized_key:
        user: root  
        key: "{{ keys }}"
        state: present
        exclusive: true

    - name: Add Docker GPG apt Key
      get_url:
        apt_key: 
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present

    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure /opt/nginx directory exists
      file:
        path: /opt/nginx
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create docker compose file
      template:
        src: ../templates/docker-compose.j2
        dest: /opt/nginx/docker-compose.yaml
        owner: root
        group: root
        mode: 0644

    - name: Create nginx cache file
      template:
        src: ../templates/cache.conf.j2
        dest: /opt/nginx/cache.conf
        owner: root
        group: root
        mode: 0644

    - name: Start nginx docker image
      shell: |
        docker compose -f /opt/nginx/docker-compose.yaml up -d
